### ISSUE TITLE
Explainable Knowledge Discovery on DBpedia

### ISSUE THREAD

**Issue by mommi84** [dbpedia/GSoC#33]
# Description
The [latest DBpedia release](http://downloads.dbpedia.org/databus/data/core/) comprises a knowledge graph having 326,035,765 edges. As the data originates from a human-generated wiki, the graph is far from being complete. This project idea aims at the realisation of an algorithm to perform **knowledge base completion** (or link prediction) on DBpedia. We want to tackle this problem using a rule-based approach in order to meet the requirements for an **explainable AI**.

# Goals
The goals of the candidate would be to adapt the code of and employ [HornConcerto](https://github.com/mommi84/horn-concerto), an algorithm to discover Horn rules and new relationships in large graphs. The method has already shown to outperform existing approaches in terms of runtime and memory consumption and mine high-quality rules for the completion task. 

Ultimate goals:
* discover explainable hidden patterns among DBpedia entities and properties;
* evaluate the algorithm on a knowledge base completion benchmark;
* write a scientific paper.

# Impact
The project will enhance the quality and completeness of DBpedia data.

# Warm-up tasks
* Read the paper:
  * [Beyond Markov Logic: Efficient Mining of Prediction Rules in Large Graphs (2018)](https://arxiv.org/abs/1802.03638) (working paper)
  * Follow the examples and run [the code](https://github.com/mommi84/horn-concerto).
  * Discover rules and new relationships in a dataset of your choice (also unrelated with DBpedia).
* [Example of successful project proposal](http://tommaso-soru.it/files/misc/Akshay-DBpedia-GSoC-2017-proposal.pdf).

# Mentors
TBD _(possible names: Tommaso Soru, Aman Mehta, Amandeep Srivastava)_.

# Keywords
knowledge discovery, knowledge base completion, link prediction, explainable artificial intelligence, association rules

**Comment by srivama** [comment]
I’d like to co-mentor this project @sandrapraetor

**Comment by g-laz77** [comment]
Hi, 
I would like to work on this project. From what I understand it looks like an exploratory project where I have to analyse sets of data to recognize patterns(rules). Will this also involve working on  any ML algorithm to learn the pattern?

**Comment by mommi84** [comment]
Hi @g-laz77 and thanks for your interest.

Yes, the proposed algorithm [HornConcerto](https://github.com/mommi84/horn-concerto) just performs a basic mining of rules and their confidence values. It can definitely be improved with ML and I recommend to include it in the project proposal. Did you think of any ML algorithm in particular?

**Comment by g-laz77** [comment]
@mommi84 I have gone through the paper [Beyond Markov Logic: Efficient Mining of Prediction Rules in Large Graphs (2018)](https://arxiv.org/pdf/1802.03638.pdf). I have understood how the basic mining of rules is done by calculating the confidence score of a said rule. This is done by simply checking the co-occerence of that rule with the top P properties(their highest occurence counts) to get the rule support and dividing it with the body support(of the P properties). 

It occurred to me to use a pattern detection ML algorithm to mine more rules. [LinkNBed: Multi-Graph Representation Learning with Entity Linkage](http://www.aclweb.org/anthology/P18-1024). Something like this?

**Comment by mommi84** [comment]
@g-laz77 The LinkNBed paper does indeed target also link prediction using representation learning. However, it is well known that deep learning models often lack the possibility to explain their own predictions. How do you expect to address this problem?

**Comment by g-laz77** [comment]
@mommi84 I agree. Deep learning models have the problem of model interpretebality. Although, I recently came across this library in python called [Skater](https://github.com/datascienceinc/Skater),  which is a unified framework to enable Model Interpretation. Since this is an exploratory project, would it not serve the purpose along with using `hornConcerto` to mine more rules?

**Comment by mommi84** [comment]
@g-laz77 It sounds worth exploring to me. Please elaborate how you would proceed in a Google doc and share it with my GitHub handle at gmail dot com.

**Comment by ky-zhang** [comment]
Hi,
I have gone through the paper **Beyond Markov Logic: Efficient Mining of Prediction Rules in Large Graphs**. I have previously worked on two papers related to graphs in C++ and python. Now I am working on a research project related to adversarial learning on graphs. So it would be a great opportunity for me to work on this project. What should I do next if I want to start contribution to this project?

**Comment by Saichethan** [comment]
Is this still open I want to be mentor how can I know if I am eligible

**Comment by mommi84** [comment]
@ky-zhang Hi and thanks for your interest! Can you please post the links to the two papers? If you have completed the warm-up tasks, the next step would be to outline a possible integration of adversarial learning or any other ML technique with the project. Prepare a draft and invite my GitHub handle at gmail dot com.

@Saichethan Hi! You can mentor a project in one of the following cases: 1. you have already been a DBpedia GSoC mentor or student; 2. you have already been a GSoC mentor for another organisation; 3. you already have published research experience in the field.

**Comment by ky-zhang** [comment]
@mommi84 Thank you for your reply. The papers haven't been published, I will send you an email with the draft papers and a pre-proposal for the project.

**Comment by g-laz77** [comment]
@mommi84 I have sent you an email with a starter plan for the proposal around a week ago. Have you received it?

**Comment by mommi84** [comment]
Yes, @g-laz77. I've forwarded it to the other mentors and we will get back to you tomorrow.

**Comment by g-laz77** [comment]
@mommi84 I have completed the proposal. Kindly review it
