### ISSUE TITLE
Dataset recommendation system in databus for several analysis. Integrating chatbot with the main website and DBpedia databus to get the dataset information.

### ISSUE THREAD

**Issue by karankharecha** [dbpedia/GSoC#38]
### Description

Currently, the chatbot is not available on the **main website** and enhancing the chatbot by integrating it with the main website and DBpedia databus for dataset information would do a great deal for users. Firstly, the scope of chatbot will be increased by adding more narrations and dialogues in order to generate more relevant responses. Another functionality is **recommendation system** of dataset in **data bus**.

### Goals

The goal of this system is basically to reduce the task of managing the activities. Instead of finding the dataset and its information by going through the website and number of datasets, users can ask the chatbot to get that job done, and in response user can get directly what they have asked for with in few seconds. On the other hand, recommendation system will be used in databus for recommending datasets to all the users. These recommendations will be given by chatbot itself.

### Impact

This project will reduce the amount of time spend on several activities and increase interactivity with the chatbot that will be integrated with the main website. More interactivity with bot will eventually increase the scope of it day by day.

### Keywords

Natural Language Processing, Data Analysis, Recommendation System.

**Comment by ram-g-athreya** [comment]
Hi @karankharecha 

Could you please elaborate on what exact activities that you envision the chatbot to manage with regards to finding datasets or with regards to the Databus integration. Example queries and/or an example user flow would also be helpful if possible.

Thanks
Ram G Athreya

**Comment by karankharecha** [comment]
Hello @ram-g-athreya 

The enhancement thing that I'm talking about is that, chatbot should be able to respond to user whenever user queries about any dataset. Right now chatbot answers general questions like:

where is berlin? and user receives the response about berlin.

But if the question is like: Provide historical data of weather in Berlin?

It won't provide the dataset. Furthermore, when it comes to accessing the dataset information, chatbot isn't responding in the way it should. Basically whatever data, DBpedia is collecting is not reflecting in the existing chatbot. DBpedia has too much data but users are unaware of it, so by enlightening users with it they can download/access it directly by querying the chatbot and we can provide more interactivity.

The main thing is to focus more on providing data that is collected by dbpedia or stored in databus.
